Vagrant.configure("2") do |config|
  # Configuration commune
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Machine ubuntu pour docker
  config.vm.define "ubuntu-docker" do |ubuntu_docker|
    ubuntu_docker.vm.box = "ubuntu/focal64"
    ubuntu_docker.vm.box_version = "20240821.0.1"
    ubuntu_docker.vm.hostname = "ubuntu-docker"
    ubuntu_docker.ssh.username = "vagrant"
    ubuntu_docker.vm.network "private_network", ip: "192.168.2.24"
    ubuntu_docker.vm.network "forwarded_port", guest: 80 , host:5000
    ubuntu_docker.vm.provision "shell", path: "provision_ubuntu_docker.sh"
    ubuntu_docker.vm.synced_folder "./dossier_ansible/docker_lab/docker_file", "/home/vagrant/docker_files", mount_options: ["dmode=777", "fmode=777"]
  end

  # Machine Ubuntu pour Ansible
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.box_version = "20240821.0.1"
    ubuntu.vm.hostname = "ubuntu-ansible"
    ubuntu.ssh.username = "vagrant"
    ubuntu.vm.network "private_network", ip: "192.168.2.20"
    ubuntu.vm.provision "shell", path: "provision_ubuntu.sh"
    ubuntu.vm.synced_folder "./dossier_ansible", "/home/vagrant/dossier_partage"
  end

  # Machine Fedora
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "generic/fedora37"
    fedora.vm.box_version = "4.3.12"
    fedora.vm.hostname = "fedora"
    fedora.ssh.username = "vagrant"
    fedora.vm.network "private_network", ip: "192.168.2.21"
    fedora.vm.provision "shell", path: "provision_fedora.sh"
  end

  # config.vm.define "fedora1" do |fedora1|
  #   fedora1.vm.box = "generic/fedora37"
  #   fedora1.vm.box_version = "4.3.12"
  #   fedora1.vm.hostname = "fedora"
  #   fedora1.ssh.username = "vagrant"
  #   fedora1.vm.network "private_network", ip: "192.168.2.25"
  #   fedora1.vm.provision "shell", path: "provision_fedora.sh"
  # end

  # Machine Arch Linux
  config.vm.define "archlinux" do |arch|
    arch.vm.box = "generic/arch"
    arch.vm.box_version = "4.3.12"
    arch.vm.hostname = "archlinux"
    arch.ssh.username = "vagrant"
    arch.vm.network "private_network", ip: "192.168.2.22"
    arch.vm.provision "shell", path: "provision_arch.sh"
  end

  # config.vm.define "archlinux1" do |arch1|
  #   arch1.vm.box = "generic/arch"
  #   arch1.vm.box_version = "4.3.12"
  #   arch1.vm.hostname = "archlinux"
  #   arch1.ssh.username = "vagrant"
  #   arch1.vm.network "private_network", ip: "192.168.2.26"
  #   arch1.vm.provision "shell", path: "provision_arch.sh"
  # end

  # Machine Debian
  config.vm.define "debian12" do |debian12|
    debian12.vm.box = "generic/debian12"
    debian12.vm.box_version = "4.3.12"
    debian12.vm.hostname = "debian12"
    debian12.ssh.username = "vagrant"
    debian12.vm.network "private_network", ip: "192.168.2.23"
    debian12.vm.provision "shell", path: "provision_debian.sh"
  end

  # config.vm.define "debian2" do |debian2|
  #   debian2.vm.box = "generic/debian12"
  #   debian2.vm.box_version = "4.3.12"
  #   debian2.vm.hostname = "debian12"
  #   debian2.ssh.username = "vagrant"
  #   debian2.vm.network "private_network", ip: "192.168.2.27"
  #   debian2.vm.provision "shell", path: "provision_debian.sh"
  # end

end
